### ISSUE TITLE
大佬您好，请问做一个这样的编译器有哪些书可以参考的？

### ISSUE THREAD

**Issue by EndlessCheng** [elvin-du/tinyscript#1]

**Comment by schwarzeni** [comment]
他这个八成是参考[慕课网这个课程: 大学计算机必修课新讲--编译原理+操作系统+图形学](https://coding.imooc.com/class/432.html)里写的编译器的，项目代码结构都是一样的。课程中用的是 Java 和 JavaScript 实现的，他这里翻译成了 Go 语言
